version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    versioning-strategy: 'auto'
    allow:
      - dependency-type: 'all'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automerge'
    groups:
      dev-dependencies:
        patterns:
          - '@types/*'
          - 'eslint*'
          - '@vitejs/*'
          - 'prettier'
          - 'typescript*'
          - 'vite*'
          - 'vitest*'
          - '@playwright/*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      runtime-dependencies:
        patterns:
          - '@radix-ui/*'
          - '@tailwindcss/*'
          - 'class-variance-authority'
          - 'clsx'
          - 'lucide-react'
          - 'react'
          - 'react-dom'
          - 'tailwind-merge'
          - 'tailwindcss'
          - 'cva'
          - 'lucide-react'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
